language: ruby
rvm:
  - 1.9.3
install:
  - curl -sLo /tmp/mono.gpg http://download.mono-project.com/repo/xamarin.gpg
  - sudo apt-key add /tmp/mono.gpg
  - sudo bash -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update
  - sudo apt-get install mono-devel
  - sudo apt-get install gettext
  - gem install rake
  - gem install albacore --version "1.0.0.rc2"
  - echo \#\!/bin/bash >> ./travis.sh
  - echo set -e >> ./travis.sh
  - echo set -x >> ./travis.sh
  - echo set -o pipefail >> ./travis.sh
  - echo echo Running on Mono 3.x >> ./travis.sh
  - echo rake mono >> ./travis.sh
  - chmod +x ./travis.sh
  - cat travis.sh
script: ./travis.sh
notifications:
  email:
    - nancy@nancyfx.org
gemfile: Gemfile
